In [1]:
import numpy as np
myarr = np.array([[1,2,3] , [4,5,6] , [9,8,7] , [6,5,9]])

In [3]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 9]])

In [4]:
flat = myarr.flatten()

In [5]:
flat

array([1, 2, 3, 4, 5, 6, 9, 8, 7, 6, 5, 9])

In [6]:
flat[:5]

array([1, 2, 3, 4, 5])

In [7]:
flat[5:]

array([6, 9, 8, 7, 6, 5, 9])

In [8]:
b = flat[3:7]

In [9]:
b

array([4, 5, 6, 9])

In [10]:
b[0] = 8967

In [11]:
b

array([8967,    5,    6,    9])

In [12]:
flat

array([   1,    2,    3, 8967,    5,    6,    9,    8,    7,    6,    5,
          9])

In [14]:
arr = np.array([1,23,89,34,67,90])

In [17]:
arr[[1,4,3]]

array([23, 67, 34])

In [18]:
arr[arr>3]

array([23, 89, 34, 67, 90])