In [1]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr , axis=1)

array([ 6, 15, 24])

In [4]:
np.sum(arr , axis=0)

array([12, 15, 18])

In [5]:
arr[0][1]

np.int64(2)

In [6]:
arr[0,1]

np.int64(2)

In [11]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [12]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [13]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [14]:
arr3D[:,0,:] = 0

In [15]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])