In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,4,6])

In [3]:
arr

array([1, 2, 4, 6])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [7]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [9]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [10]:
myarr = np.array([[1,2,3] , [4,5,6] , [9,8,7] , [6,5,9]])

In [11]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 9]])

In [12]:
myarr.shape

(4, 3)

In [13]:
myarr.size

12

In [14]:
myarr = np.array([[1,2,3] , [4,5,6] , [9,8,7] , [6,5,9]], dtype='float32')

In [15]:
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [9., 8., 7.],
       [6., 5., 9.]], dtype=float32)

In [16]:
n = myarr.astype('float64')

In [17]:
n.dtype

dtype('float64')

In [18]:
myarr.dtype

dtype('float32')